version: '3.4'

services:
  medicine:
    image: medicine-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - medicine-network
    depends_on:
      - mssql

  mssql:
    image: microsoft/mssql-server-linux
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
    restart: unless-stopped
    networks:
      - medicine-network
    ports:
      - "1433:1433"

volumes:
  mssql-server-linux-data:

networks:
  medicine-network:
    driver: bridge